# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site language
lang: en-US

# Site title
title: "Big Data Mining Lab"

# A description of your site for meta tag, search engine results.
description: "BDML 세미나 정리 블로그"

# The subpath of your site, e.g. /blog, for generating urls.
baseurl: ""

# The base hostname & protocol of your site for where absolute urls are needed.
url: "https://bdml-study.github.io/"

# Favicon
favicon: images/favicon.png

# Google Analytics id, e.g. "UA-NNNNNNNN-N"
google_analytics: ""

# Site navigation - each item must have a title and a url.
navigation:
  - text: Home
    url: /
  - text: About
    url: /about/
  # - text: Style Guide
  #   url: /style-guide/
  - text: GitHub
    url: https://github.com/hyerica-bdml
    # url: https://github.com/JustGoodThemes/Scriptor-Jekyll-Theme
  # - text: Tags
  #   url: /tags/

# The shortname for your Disqus site to enable comments.
disqus: bdml

# Colors
accent_color: '#9bbb59'

# Site footer
footer:
  content: "&copy; Scriptor all rights reserved. Theme by [JustGoodThemes](https://www.justgoodthemes.com)."
  has_social: true

# Plugins
plugins:
  - jekyll-paginate

# http://jekyllrb.com/docs/pagination/
paginate: 3
paginate_path: '/page:num/'


# Permalinks
permalink: /:title

# Conversion
markdown: kramdown
mathjax: true
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Sass
sass:
  sass_dir: _sass
  style: compressed

timezone: Asia/Seoul
future: true